feat[abi]:add elector and tonstakers abi json
tonindexer/anton pull request #43
Opened 2024-10-15 10:28 UTC by fishTsai20

2024-10-15 10:30 UTC, iam047801 commented on .env
Should remove this file.

2024-10-15 10:33 UTC, iam047801 commented
Thank you. I will test it and merge it.

2024-10-15 10:34 UTC, iam047801 commented
Also need to resolve conflicts with `v0.4.2-dev` branch.

2024-10-16 04:49 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "format": "controller_data"
No definition for this structure.

2024-10-16 04:50 UTC, iam047801 commented on abi/known/tonstakers.json
> +      "pool_params": [
This structure from DeDust is not used here.

2024-10-16 04:51 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "format": "msg_address"
For address, should use `addr` in both format and tlb_type fields.

2024-10-16 04:51 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "tlb_type": "Bool",
`tlb_type` should be `bool`.

2024-10-16 04:52 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "format": "uint48"
`uint48` is not supported. Use `uint64`.

2024-10-16 04:52 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "format": "uint"
`uint` is not supported.

2024-10-16 04:53 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "tlb_type": "Coins",
`tlb_type` here should probably be `.`.

2024-10-16 04:55 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "tlb_type": "(Maybe ^Cell)",
Use `maybe ^` instead.

2024-10-16 04:56 UTC, iam047801 commented on abi/known/tonstakers.json
> +        "name": "get_pool_params",
`get_pool_addr` and `get_pool_params` are copied from DeDust ABI and should not be here.

2024-10-16 04:59 UTC, iam047801 commented on abi/known/tonstakers.json
> +    "interface_name": "tonstakers_controller",
Interface should have either code, get_methods or addresses.

2024-10-16 05:00 UTC, iam047801 commented on abi/known/tonstakers.json
> +        "parameters": [
There is no field `parameters`. You can use [json schema](https://github.com/tonindexer/anton/blob/main/abi/abi.schema.json).

2024-10-16 05:00 UTC, iam047801 commented on abi/known/tonstakers.json
> +            "format": "slice | null"
Such format is not supported.

2024-10-16 05:02 UTC, iam047801 requested changes
Described ABI is not working yet.

2024-10-17 09:55 UTC, mm8191 approved these changes

2024-10-24 15:52 UTC, mm8191 approved these changes

2024-10-24 15:53 UTC, mm8191 commented on abi/known/tonstakers.json
> +            "format": "controller_data"
Comment8191

2025-06-26 12:52 UTC, closed without merging